import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


def _uuid() -> str:
    return str(uuid.uuid4())


class Supplier(Base):
    __tablename__ = "suppliers"

    id = Column(String, primary_key=True, default=_uuid)
    name = Column(String, nullable=False)
    country_code = Column(String(2), nullable=False, index=True)
    region = Column(String, nullable=True)
    product_category = Column(String, nullable=False)
    tier = Column(Integer, nullable=False, default=1)
    lat = Column(Float, nullable=True)
    lng = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    risk_scores = relationship("RiskScore", back_populates="supplier")
    forecasts = relationship("Forecast", back_populates="supplier")


class Event(Base):
    __tablename__ = "events"

    id = Column(String, primary_key=True, default=_uuid)
    source = Column(String, nullable=False)  # gdelt | newsapi | noaa
    headline = Column(Text, nullable=False)
    url = Column(String, nullable=False, unique=True)  # dedup key
    category = Column(String, nullable=False)  # weather|geopolitical|logistics|labor|cyber
    affected_countries = Column(JSON, nullable=False, default=list)
    severity_hint = Column(String, nullable=False, default="medium")  # low|medium|high
    is_supply_chain_relevant = Column(Boolean, default=True)
    brief_reason = Column(Text, nullable=True)
    published_at = Column(DateTime, nullable=True)
    ingested_at = Column(DateTime, default=datetime.utcnow)

    risk_scores = relationship("RiskScore", back_populates="event")


class RiskScore(Base):
    __tablename__ = "risk_scores"
    __table_args__ = (
        UniqueConstraint("event_id", "supplier_id", name="uq_event_supplier"),
    )

    id = Column(String, primary_key=True, default=_uuid)
    event_id = Column(String, ForeignKey("events.id"), nullable=False, index=True)
    supplier_id = Column(String, ForeignKey("suppliers.id"), nullable=False, index=True)
    score = Column(Integer, nullable=False)  # 1-10
    impact_window = Column(String, nullable=False)  # '24h', '72h', '1-2 weeks', etc.
    affected_tiers = Column(JSON, default=list)
    reasoning = Column(Text, nullable=False)
    scored_at = Column(DateTime, default=datetime.utcnow)

    event = relationship("Event", back_populates="risk_scores")
    supplier = relationship("Supplier", back_populates="risk_scores")
    alert = relationship("Alert", back_populates="risk_score", uselist=False)


class EconomicSignal(Base):
    """Time-series snapshots of macro economic indicators (WTI, BDI proxy, copper, food index…)."""
    __tablename__ = "economic_signals"
    __table_args__ = (
        UniqueConstraint("indicator", "date", name="uq_signal_date"),
    )

    id = Column(String, primary_key=True, default=_uuid)
    indicator = Column(String, nullable=False, index=True)   # e.g. "WTI_CRUDE", "COPPER", "FOOD_INDEX"
    value = Column(Float, nullable=False)
    change_pct_30d = Column(Float, nullable=True)            # % change vs 30 days prior
    date = Column(DateTime, nullable=False)
    source = Column(String, nullable=False, default="fred")  # fred | worldbank | yahoo
    fetched_at = Column(DateTime, default=datetime.utcnow)


class Forecast(Base):
    """Multi-horizon disruption probability forecast per supplier, generated by Agent 5 (Forecaster)."""
    __tablename__ = "forecasts"

    id = Column(String, primary_key=True, default=_uuid)
    supplier_id = Column(String, ForeignKey("suppliers.id"), nullable=False, index=True)
    industry = Column(String, nullable=False)
    horizon = Column(String, nullable=False)              # "15d" | "30d" | "3m" | "6m" | "1y" | "2y"
    disruption_probability = Column(Float, nullable=False)  # 0.0 – 1.0
    confidence = Column(String, nullable=False)           # "high" | "medium" | "low"
    drivers = Column(JSON, default=list)                  # top 3 driving factors
    scenario = Column(Text, nullable=True)
    overall_trend = Column(String, nullable=True)         # "escalating" | "stable" | "improving"
    created_at = Column(DateTime, default=datetime.utcnow)

    supplier = relationship("Supplier", back_populates="forecasts")

    __table_args__ = (
        Index("ix_forecast_supplier_horizon", "supplier_id", "horizon"),
    )


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(String, primary_key=True, default=_uuid)
    risk_score_id = Column(String, ForeignKey("risk_scores.id"), nullable=False, index=True)
    level = Column(String, nullable=False)  # HIGH | MEDIUM | LOW
    brief = Column(Text, nullable=True)
    alternatives = Column(JSON, default=list)
    dispatched_via = Column(JSON, default=list)  # ['slack', 'email']
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    risk_score = relationship("RiskScore", back_populates="alert")
